// DLP Shield - Content Script (De-anonymization Engine)
// Runs on AI chat pages and restores original PII values from synthetic placeholders

console.log("🛡️ DLP Shield Extension loaded - monitoring for synthetic data");

// ── Configuration ─────────────────────────────────────────────────────────────
// Default server URL; overridden at runtime from chrome.storage
let DLP_SERVER_URL = "http://localhost:3000";
const SCAN_INTERVAL = 500; // debounce ms

// Load persisted server URL from storage
chrome.storage.local.get(["serverUrl", "enabled"], (data) => {
  if (data.serverUrl) DLP_SERVER_URL = data.serverUrl;
  // Respect the enabled toggle - don't scan if disabled
  if (data.enabled === false) return;
  // Run an initial scan once settings are loaded
  setTimeout(scanForSyntheticData, 2000);
});

// ── Session-scoped cache: synthetic → { found, originalText, category, label } ─
const resolvedCache = new Map();

// ── Already-processed nodes (avoid re-processing) ─────────────────────────────
const processedNodes = new WeakSet();

// ── Synthetic data detection patterns ─────────────────────────────────────────
// These match the FORMAT of data generated by syntheticGenerator.js
const SYNTHETIC_PATTERNS = [
  { regex: /05\d-\d{7}/g,          category: "PHONE"       },
  { regex: /0[2-9]-\d{7}/g,        category: "LANDLINE"    },
  { regex: /\b3\d{8}\b/g,          category: "ID"          },
  { regex: /user_\d{3}@gmail\.com/g, category: "EMAIL"     },
  { regex: /4\d{3}-\d{4}-\d{4}-\d{4}/g, category: "CREDIT_CARD" },
];

// ── AI chat container selectors (per platform) ─────────────────────────────────
const AI_SELECTORS = [
  // ChatGPT / OpenAI
  'div[data-message-author-role="assistant"]',
  ".markdown",
  ".result-streaming",
  // Claude
  "div.font-claude-message",
  ".prose",
  // Gemini
  ".response-container",
  ".model-response-text",
];

// ── Debounce helper ───────────────────────────────────────────────────────────
let scanTimer = null;
function debouncedScan() {
  clearTimeout(scanTimer);
  scanTimer = setTimeout(scanForSyntheticData, SCAN_INTERVAL);
}

// ── MutationObserver: watch DOM for new AI response content ───────────────────
const observer = new MutationObserver((mutations) => {
  // Only react if there are actual node additions
  const hasAdditions = mutations.some(
    (m) => m.type === "childList" && m.addedNodes.length > 0
  );
  if (hasAdditions) debouncedScan();
});

observer.observe(document.body, { childList: true, subtree: true });

// ── Listen for settings changes from popup ────────────────────────────────────
chrome.runtime.onMessage.addListener((message) => {
  if (message.type === "SETTINGS_UPDATED") {
    if (message.serverUrl) DLP_SERVER_URL = message.serverUrl;
  }
});

// ── Main scan function ─────────────────────────────────────────────────────────
function scanForSyntheticData() {
  // Find AI response containers; fall back to body if nothing matches
  let containers = [];
  for (const selector of AI_SELECTORS) {
    const found = document.querySelectorAll(selector);
    if (found.length) {
      containers.push(...found);
    }
  }
  if (containers.length === 0) containers = [document.body];

  // Collect all text nodes inside containers
  const textNodes = [];
  for (const container of containers) {
    collectTextNodes(container, textNodes);
  }

  // Collect all synthetic matches (deduplicated by value)
  const pendingLookups = new Map(); // syntheticValue → [{ node, startIndex }]

  for (const node of textNodes) {
    if (processedNodes.has(node)) continue;
    const text = node.nodeValue;
    if (!text || text.trim().length === 0) continue;

    for (const { regex, category } of SYNTHETIC_PATTERNS) {
      regex.lastIndex = 0;
      let m;
      while ((m = regex.exec(text)) !== null) {
        const val = m[0];
        // Skip if already cached as "not found"
        if (resolvedCache.has(val) && !resolvedCache.get(val).found) continue;
        if (!pendingLookups.has(val)) pendingLookups.set(val, []);
        pendingLookups.get(val).push({ node, category });
      }
    }
  }

  if (pendingLookups.size === 0) return;

  // Separate into cached (already resolved) vs needs fetch
  const toFetch = [];
  for (const [synthetic] of pendingLookups) {
    if (!resolvedCache.has(synthetic)) {
      toFetch.push(synthetic);
    }
  }

  // Apply already-cached replacements immediately
  for (const [synthetic, occurrences] of pendingLookups) {
    if (resolvedCache.has(synthetic)) {
      const result = resolvedCache.get(synthetic);
      if (result.found) {
        for (const { node } of occurrences) {
          replaceInDOM(node, synthetic, result.originalText, result.label);
        }
      }
    }
  }

  // Batch fetch all uncached synthetic values in parallel
  if (toFetch.length === 0) return;

  // Use restore-batch endpoint for efficiency
  fetchBatch(toFetch)
    .then((batchResults) => {
      for (const [synthetic, result] of Object.entries(batchResults)) {
        resolvedCache.set(synthetic, result);
        const occurrences = pendingLookups.get(synthetic) || [];
        if (result.found) {
          for (const { node } of occurrences) {
            replaceInDOM(node, synthetic, result.originalText, result.label);
          }
        }
      }

      // Report stats to background service worker
      const restoredCount = Object.values(batchResults).filter((r) => r.found).length;
      if (restoredCount > 0) {
        chrome.runtime.sendMessage({ type: "ITEMS_RESTORED", count: restoredCount }).catch(() => {});
      }
    })
    .catch((err) => {
      console.warn("[DLP Shield] Batch fetch failed:", err);
    });
}

// ── Batch fetch using /api/restore-batch ──────────────────────────────────────
async function fetchBatch(tags) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 5000);
  try {
    const res = await fetch(`${DLP_SERVER_URL}/api/restore-batch`, {
      method: "POST",
      headers: { "Content-Type": "application/json", "x-dlp-extension": "1" },
      body: JSON.stringify({ tags }),
      signal: controller.signal,
    });
    clearTimeout(timeout);
    if (!res.ok) return {};
    const data = await res.json();
    return data.results || {};
  } catch (err) {
    clearTimeout(timeout);
    return {};
  }
}

// ── Single tag fetch (fallback) ───────────────────────────────────────────────
async function fetchOriginal(tag) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 5000);
  try {
    const res = await fetch(
      `${DLP_SERVER_URL}/api/check-text?tag=${encodeURIComponent(tag)}`,
      {
        signal: controller.signal,
        headers: { "x-dlp-extension": "1" },
      }
    );
    clearTimeout(timeout);
    if (!res.ok) return null;
    return await res.json();
  } catch (err) {
    clearTimeout(timeout);
    return null;
  }
}

// ── DOM replacement ───────────────────────────────────────────────────────────
function replaceInDOM(textNode, synthetic, original, label) {
  if (!textNode.parentNode) return;
  // Skip if this node was already removed or replaced
  if (!document.contains(textNode)) return;

  const text = textNode.nodeValue;
  const idx = text.indexOf(synthetic);
  if (idx === -1) return;

  // Split text into before / replaced / after
  const before = text.slice(0, idx);
  const after = text.slice(idx + synthetic.length);

  const fragment = document.createDocumentFragment();

  if (before) fragment.appendChild(document.createTextNode(before));

  const span = document.createElement("span");
  span.className = "dlp-restored dlp-restored-new";
  span.title = "🛡️ DLP Shield: מידע מוגן שוחזר";
  span.setAttribute("data-dlp-original", "true");
  span.setAttribute("data-dlp-synthetic", synthetic);
  span.textContent = original;
  fragment.appendChild(span);

  if (after) fragment.appendChild(document.createTextNode(after));

  textNode.parentNode.replaceChild(fragment, textNode);

  // Remove the "new" animation class after it completes
  setTimeout(() => span.classList.remove("dlp-restored-new"), 1600);
}

// ── Walk DOM for text nodes ───────────────────────────────────────────────────
function collectTextNodes(root, result) {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
    acceptNode(node) {
      // Skip script / style / already-processed dlp spans
      const parent = node.parentElement;
      if (!parent) return NodeFilter.FILTER_REJECT;
      const tag = parent.tagName;
      if (tag === "SCRIPT" || tag === "STYLE" || tag === "NOSCRIPT") return NodeFilter.FILTER_REJECT;
      if (parent.classList && parent.classList.contains("dlp-restored")) return NodeFilter.FILTER_REJECT;
      return NodeFilter.FILTER_ACCEPT;
    },
  });

  let node;
  while ((node = walker.nextNode())) {
    result.push(node);
  }
}
